worker_processes  1;

events {}

http {

  absolute_redirect off;
  # DNS Dockera (żeby nginx mógł rozwiązywać nazwy serwisów)
  resolver 127.0.0.11 ipv6=off valid=10s;

  # sensowne logi
  access_log /var/log/nginx/access.log;
  error_log  /var/log/nginx/error.log warn;

  # wczytaj pliki vhostów
  include /etc/nginx/conf.d/*.conf;
}
