# Upstreamy na nazwy serwisów z docker-compose
upstream producer_upstream {
  server producer:8080;
  keepalive 32;
}

upstream consumer_upstream {
  server consumer:8081;
  keepalive 32;
}

upstream kafka_ui_upstream {
  server kafka-ui:8080;
  keepalive 16;
}

server {
  listen 80;
  server_name _;

  # Health NGINX (do docker healthcheck i LB)
  location = /healthz {
    add_header Content-Type text/plain;
    return 200 "ok\n";
  }

  # Producer API
  location /events {
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_connect_timeout 5s;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;

    proxy_pass http://producer_upstream;
  }

  # Kafka UI pod /kafka/
  location /kafka/ {
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Prefix /kafka;

    proxy_pass http://kafka_ui_upstream/;
  }

  # (opcjonalnie) consumer pod /consumer/
  location /consumer/ {
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_pass http://consumer_upstream/;
  }

  location / {
    return 404;
  }
}
